name: Build APK

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # or your preferred Node.js version

    - name: Install dependencies
      run: |
        cd BookBard
        npm install

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build APK
      run: |
        pwd;
        ls;
        cd BookBard/android
        ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/app-release.apk
